engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
      linebreak-style:
        enabled: false
  fixme:
    enabled: true
ratings:
    paths:
      - "server/**/*.js"
      - "client/**/*.js"
languages:
  JavaScript: true
exclude_paths:
  - "node_modules/"
  - "template/css/"
  - "template/.sass-cache/"
  - "template/font/"
  - "template/scss/"
  - "template/js/"
  - "server/routes/"
  - "server/test"